### ISSUE TITLE
Disconnect event does not fire reliably

### ISSUE THREAD

**Issue by NeoLegends** [autovance/ftp-srv#178]
Hey!

I've been trying to use the new disconnect event from #175, but I noticed it doesn't fire reliably. I tested it by setting the timeout option to 30s, connecting with an FTP client and waiting for the event, but it never fires. What does happen, however, is that writing to the socket fails. However, that error is logged and swallowed, and not forwarded to the `client-error` event (which would lead to `disconnect` being fired).

The attached log is the socket write failure, which is swallowed here: https://github.com/trs/ftp-srv/blob/a18841d770fb0c3593b0109490105c329912824a/src/connection.js#L148

```[1573642972074] ERROR (SocketError): Socket not writable
    SocketError: Socket not writable
        at /Users/moritzgunz/Documents/Projekte/dekema-ftp/node_modules/ftp-srv/src/connection.js:139:23
        at Promise._execute (/Users/moritzgunz/Documents/Projekte/dekema-ftp/node_modules/bluebird/js/release/debuggability.js:411:9)
        at Promise._resolveFromExecutor (/Users/moritzgunz/Documents/Projekte/dekema-ftp/node_modules/bluebird/js/release/promise.js:518:18)
        at new Promise (/Users/moritzgunz/Documents/Projekte/dekema-ftp/node_modules/bluebird/js/release/promise.js:103:10)
        at processLetter (/Users/moritzgunz/Documents/Projekte/dekema-ftp/node_modules/ftp-srv/src/connection.js:129:14)
        at /Users/moritzgunz/Documents/Projekte/dekema-ftp/node_modules/ftp-srv/src/connection.js:145:14
        at tryCatcher (/Users/moritzgunz/Documents/Projekte/dekema-ftp/node_modules/bluebird/js/release/util.js:16:23)
        at Object.gotValue (/Users/moritzgunz/Documents/Projekte/dekema-ftp/node_modules/bluebird/js/release/reduce.js:166:18)
        at Object.gotAccum (/Users/moritzgunz/Documents/Projekte/dekema-ftp/node_modules/bluebird/js/release/reduce.js:155:25)
        at Object.tryCatcher (/Users/moritzgunz/Documents/Projekte/dekema-ftp/node_modules/bluebird/js/release/util.js:16:23)
        at Promise._settlePromiseFromHandler (/Users/moritzgunz/Documents/Projekte/dekema-ftp/node_modules/bluebird/js/release/promise.js:547:31)
        at Promise._settlePromise (/Users/moritzgunz/Documents/Projekte/dekema-ftp/node_modules/bluebird/js/release/promise.js:604:18)
        at Promise._settlePromiseCtx (/Users/moritzgunz/Documents/Projekte/dekema-ftp/node_modules/bluebird/js/release/promise.js:641:10)
        at _drainQueueStep (/Users/moritzgunz/Documents/Projekte/dekema-ftp/node_modules/bluebird/js/release/async.js:97:12)
        at _drainQueue (/Users/moritzgunz/Documents/Projekte/dekema-ftp/node_modules/bluebird/js/release/async.js:86:9)
        at Async._drainQueues (/Users/moritzgunz/Documents/Projekte/dekema-ftp/node_modules/bluebird/js/release/async.js:102:5)```

**Comment by trs** [comment]
Looks like this `disconnect` event will only fire if the server closes a connection explicitly. Not when a connection closes itself.
This should be fixed by https://github.com/autovance/ftp-srv/pull/208.
