### ISSUE TITLE
Socket not writable

### ISSUE THREAD

**Issue by jembach** [autovance/ftp-srv#200]
Hi,

I'm trying to implement the ftp-srv. Every time a user connects, I get the error:

```json
{
"name":"ftp-srv",
"hostname":"5921eeb2bd3b",
"pid":1,"id":"269f39b0-1cb5-48bd-aad9-c351824e54b2",
"level":50,
"err": {
   "message":"Socket not writable",
   "name":"SocketError",
   "stack":"
      SocketError: Socket not writable
      at /app/node_modules/ftp-srv/src/connection.js:139:23
      at Promise._execute (/app/node_modules/bluebird/js/release/debuggability.js:384:9)
      at Promise._resolveFromExecutor (/app/node_modules/bluebird/js/release/promise.js:518:18)
      at new Promise (/app/node_modules/bluebird/js/release/promise.js:103:10)
      at processLetter (/app/node_modules/ftp-srv/src/connection.js:129:14)
      at /app/node_modules/ftp-srv/src/connection.js:145:14
      at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
      at Object.gotValue (/app/node_modules/bluebird/js/release/reduce.js:166:18)
      at Object.gotAccum (/app/node_modules/bluebird/js/release/reduce.js:155:25)
      at Object.tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromiseCtx (/app/node_modules/bluebird/js/release/promise.js:641:10)
      at _drainQueueStep (/app/node_modules/bluebird/js/release/async.js:97:12)
      at _drainQueue (/app/node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:102:5)",
   "code":500
},
"msg":"Socket not writable",
"time":"2020-05-24T09:57:51.827Z",
"v":0
}
```

The error occurs on local development and production release. The Production release is a Dockerfile deployment.

__Version:__ 4.3.1

__Server Config:__
```javascript
 const server = new FtpSrv({
    url: process.env.FTP_URL,
    pasv_url: process.env.PASV_HOSTNAME,
    pasv_min: process.env.PASV_MIN,
    pasv_max: process.env.PASV_MAX,
    anonymous: false,
    timeout: 300
  });
```

**Comment by Nalem14** [comment]
Hi,

I got the same error, not for all users.

**Comment by trs** [comment]
I was able to see this error when I connected via web browser to the server. The timeout would trigger (300ms is really short) but the client was incorrectly calling `Socket.prototype.end` instead of `Socket.prototype.destroy` on close.
This is fixed by https://github.com/autovance/ftp-srv/pull/208

Was this similar to how you guys ran into this issue?

**Comment by jembach** [comment]
Hi, 

The fix solves my problem. 

Additionally I missed that the pasv ports must be a number. 
Previously I used the .env file with dotenv and this returns a string. Therefore it doesn't work. 

Thanks for solving this issue.
