### ISSUE TITLE
TimeoutError on RETR over TLS

### ISSUE THREAD

**Issue by Dforrunner** [autovance/ftp-srv#221]
Hey, I know a similar issue was raised before and I saw that the fix was implemented on an earlier release, but I seem to be getting the error still. Here is the log:

```json
{ 
"name":"ftp-srv",
"hostname":"test1",
"pid":7452,"id":"ad134c69-01af-4859-ba3f-5e48ae355882",
"directive":"RETR",
"level":50,
"err":{
         "message":"operation timed out",
         "name":"TimeoutError",
          "stack":"TimeoutError: operation timed out\n   at afterTimeout (C:\\Users\\mbarut\\Desktop\\node\\ftp- 
                       srv\\node_modules\\bluebird\\js\\release\\timers.js:46:19)\n    at Timeout.timeoutTimeout [as _onTimeout] 
                      (C:\\Users\\mbarut\\Desktop\\node\\ftp-srv\\node_modules\\bluebird\\js\\release\\timers.js:76:13)\n    at 
                     ontimeout (timers.js:436:11)\n    at tryOnTimeout (timers.js:300:5)\n    at listOnTimeout (timers.js:263:5)\n    at 
                   Timer.processTimers (timers.js:223:10)"},
"msg":"operation timed out",
"time":"2020-11-25T17:12:37.609Z",
"v":0
}
```

Here is my server config:
```javascript
const ftpServer = new FtpSrv({
    url: `ftps://${config.FTP_HOST}:${config.FTP_PORT}`,
    pasv_url: config.FTP_PASV,
    pasv_min: 50000,
    pasv_max: 50200,
    tls: {
        key: fs.readFileSync(config.KEY),
        cert: fs.readFileSync(config.CERT),
        ca: fs.readFileSync(config.CA)
    }
});
```

The files are listed and the auth works. I just need to be able to download files. Do you have any idea or suggestion as to how to fix the problem?

**Comment by adharsh05** [comment]
Same here. One connection established, another connection. getting this error
