### ISSUE TITLE
JS error TypeError: Cannot read property 'pipe' of null and 425 No connection established

### ISSUE THREAD

**Issue by eduha** [autovance/ftp-srv#270]
Hello!

In some cases after some time the app is running, the this.connector.socket becomes null in STOR command. 

Is anyone can suggest some fix? 

JS trace:

Unhandled rejection TypeError: Cannot read property 'pipe' of null
    at /snapshot/meta-egsv/node_modules/ftp-srv/src/commands/registration/stor.js:40:31
    at Promise._execute (/snapshot/meta-egsv/node_modules/bluebird/js/release/debuggability.js:384:9)
    at Promise._resolveFromExecutor (/snapshot/meta-egsv/node_modules/bluebird/js/release/promise.js:518:18)
    at new Promise (/snapshot/meta-egsv/node_modules/bluebird/js/release/promise.js:103:10)
    at /snapshot/meta-egsv/node_modules/ftp-srv/src/commands/registration/stor.js:39:29
    at tryCatcher (/snapshot/meta-egsv/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/snapshot/meta-egsv/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/snapshot/meta-egsv/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/snapshot/meta-egsv/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/snapshot/meta-egsv/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/snapshot/meta-egsv/node_modules/bluebird/js/release/promise.js:673:18)
    at Promise._resolveCallback (/snapshot/meta-egsv/node_modules/bluebird/js/release/promise.js:489:14)
    at Promise._settlePromiseFromHandler (/snapshot/meta-egsv/node_modules/bluebird/js/release/promise.js:559:17)
    at Promise._settlePromise (/snapshot/meta-egsv/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/snapshot/meta-egsv/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/snapshot/meta-egsv/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/snapshot/meta-egsv/node_modules/bluebird/js/release/promise.js:673:18)
    at Promise._resolveCallback (/snapshot/meta-egsv/node_modules/bluebird/js/release/promise.js:466:57)
    at Promise._settlePromiseFromHandler (/snapshot/meta-egsv/node_modules/bluebird/js/release/promise.js:559:17)
    at Promise._settlePromise (/snapshot/meta-egsv/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/snapshot/meta-egsv/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/snapshot/meta-egsv/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/snapshot/meta-egsv/node_modules/bluebird/js/release/promise.js:673:18)
    at Promise._resolveCallback (/snapshot/meta-egsv/node_modules/bluebird/js/release/promise.js:466:57)
    at Promise._settlePromiseFromHandler (/snapshot/meta-egsv/node_modules/bluebird/js/release/promise.js:559:17)
    at Promise._settlePromise (/snapshot/meta-egsv/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/snapshot/meta-egsv/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/snapshot/meta-egsv/node_modules/bluebird/js/release/promise.js:729:18)

**Comment by matt-forster** [comment]
The connection might have been closed early - or any other failure might have set the connection to null. I'm not sure what the fix is, but it is definitely on our radar. Thanks for the report.

**Comment by matt-forster** [comment]
At the very least, the error handling can be improved.
